g1 <- (ggplot(PD, aes(x = Date_Time, y = Global_active_power))
       + geom_line() + xlab("") + ylab("Global Active Power")
       + theme(axis.title.y = element_text(size = 10))
       + theme(axis.text.x=element_text(size=6), axis.text.y=element_text(size=6)))
g2 <- (ggplot(PD, aes(x = Date_Time, y = Voltage))
       + geom_line() + xlab("") + ylab("Voltage")
       + theme(axis.title.y = element_text(size = 10))
       + theme(axis.text.x=element_text(size=6), axis.text.y=element_text(size=6)))
g3 <- (ggplot(PDmelt)
       + geom_line(aes(x=Date_Time, y=value, colour=variable))
       + labs(x = "", y = "Energy sub metering")
       + theme(axis.title.y = element_text(size = 10))
       + theme(legend.justification = c(1, 1), legend.position = c(1, 1))
       + theme(legend.title = element_blank(), legend.margin = margin(unit(-12, "pt")))
       + theme(legend.key.size = unit(8, "pt"), legend.text = element_text(size=6))
       + theme(axis.text.x=element_text(size=6), axis.text.y=element_text(size=6)))
g4 <- (ggplot(PD, aes(x = Date_Time, y = Global_reactive_power))
       + geom_line() + xlab("") + ylab("Global Rective Power")
       + theme(axis.title.y = element_text(size = 10))
       + theme(axis.text.x=element_text(size=6), axis.text.y=element_text(size=6)))
grid.arrange(g1, g2, g3, g4, ncol=2, nrow=2)
